builds:
  - binary: askcloudhelloworld
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: askcloudhelloworld
    homepage: https://github.com/c3smoneky/askcloudhelloworld
    tap:
      owner: askcloudarchitech
      name: homebrew-c3smoneky
    commit_author:
      name: Marcel Widmer
      email: marzelwidmer@gmail.com

checksum:
  name_template: 'checksums.txt'
